<?php
/**
 * Created by JetBrains PhpStorm.
 * User: advanced
 * Date: 15/11/10
 * Time: 11:52 PM
 * To change this template use File | Settings | File Templates.
 */
 
class Branch extends Contact {
	
	protected function delete() {}
	protected function _read() {}
	protected function _canProcess() {}
	public function save($changes = null) {}
	protected function _new() {}
	protected function _countTransactions() {}
}
