<?php
  namespace ADV\Core;

  /**
   * Generated by PHPUnit_SkeletonGenerator on 2012-06-12 at 17:09:22.
   */
  class ConfigTest extends \PHPUnit_Framework_TestCase
  {
    /**
     * @var Config
     */
    protected $object;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $this->object = new Config;
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    /**
     * @covers ADV\Core\Config::_set
     * @todo   Implement test_set().
     */
    public function test_set()
    {
      $result = $this->object->_set('test', 'val');
      $this->assertEquals('val', $result);
      $vars = $this->readAttribute($this->object, '_vars');
      $this->assertArrayHasKey('config', $vars);
      $vars = $vars['config'];
      $this->assertArrayHasKey('test', $vars);
    }
    /**
     * @covers ADV\Core\Config::_get
     * @depnds test_set
     */
    public function test_get()
    {
      $this->object->_set('test', 'val');
      $actual = $this->object->_get('test');
      $this->assertEquals('val', $actual);
      $actual = $this->object->_get('test2', 'default');
      $this->assertEquals('default', $actual);
    }
    /**
     * @covers  ADV\Core\Config::_remove
     * @depends test_set
     */
    public function test_remove()
    {
      $this->object->_set('test', 'val');
      $vars = $this->readAttribute($this->object, '_vars');
      $this->assertArrayHasKey('config', $vars);
      $vars = $vars['config'];
      $this->assertArrayHasKey('test', $vars);
      $this->object->_remove('test');
      $vars = $this->readAttribute($this->object, '_vars');
      $this->assertArrayHasKey('config', $vars);
      $vars = $vars['config'];
      $this->assertArrayNotHasKey('test', $vars);
    }
    /**
     * @covers ADV\Core\Config::_get_all
     * @todo   Implement test_get_all().
     */
    public function test_get_all()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Config::_removeAll
     * @todo   Implement test_removeAll().
     */
    public function test_removeAll()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Config::_reset
     * @todo   Implement test_reset().
     */
    public function test_reset()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Config::_shutdown
     * @todo   Implement test_shutdown().
     */
    public function test_shutdown()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
  }
