<?php


  /**
   * Test class for Debtor.
   * Generated by PHPUnit on 2011-12-24 at 06:49:29.
   */
  class DebtorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Debtor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
      $this->object = new Debtor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testAddBranch().
     */
    public function testAddBranch() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testDelete().
     */
    public function testDelete() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGetEmailAddresses().
     */
    public function testGetEmailAddresses() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGetTransactions().
     */
    public function testGetTransactions() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testSave().
     */
    public function testSave() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testAddEditDialog().
     */
    public function testAddEditDialog() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testAddSearchBox().
     */
    public function testAddSearchBox() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testSearch().
     */
    public function testSearch() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testSearchOrder().
     */
    public function testSearchOrder() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGet_details().
     */
    public function testGet_details() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGet().
     */
    public function testGet() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGet_name().
     */
    public function testGet_name() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGet_habit().
     */
    public function testGet_habit() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGet_area().
     */
    public function testGet_area() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGet_salesman_name().
     */
    public function testGet_salesman_name() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testGet_credit().
     */
    public function testGet_credit() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testIs_new().
     */
    public function testIs_new() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testSelect().
     */
    public function testSelect() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testCells().
     */
    public function testCells() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testRow().
     */
    public function testRow() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo   Implement testTrans_view().
     */
    public function testTrans_view() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
  }

?>
