<?php


	/**
	 * Test class for Event.
	 * Generated by PHPUnit on 2012-02-25 at 03:13:25.
	 */
	class EventTest extends PHPUnit_Framework_TestCase
	{
		/**
		 * @var Event
		 */
		/**
		 * Sets up the fixture, for example, opens a network connection.
		 * This method is called before a test is executed.
		 */
		protected function setUp() {
			Event::i();
		}
		/**
		 * Tears down the fixture, for example, closes a network connection.
		 * This method is called after a test is executed.
		 */
		protected function tearDown() {
		}
		/**
		 * @covers Event::error
		 * @todo   Implement testError().
		 */
		public function testError() {
			Event::error('Error Test');
			$this->assertClassHasStaticAttribute('errors','Errors');
			$this->assertEquals(array(),Errors::$messages);
		$this->assertCount(1,Errors::$messages);
		}
		/**
		 * @covers Event::notice
		 * @todo   Implement testNotice().
		 */
		public function testNotice() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
		/**
		 * @covers Event::success
		 * @todo   Implement testSuccess().
		 */
		public function testSuccess() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
		/**
		 * @covers Event::warning
		 * @todo   Implement testWarning().
		 */
		public function testWarning() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
		/**
		 * @covers Event::register_shutdown
		 * @todo   Implement testRegister_shutdown().
		 */
		public function testRegister_shutdown() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
		/**
		 * @covers Event::shutdown
		 * @todo   Implement testShutdown().
		 */
		public function testShutdown() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
		}
	}

?>
