<?php
  namespace ADV\Core;
  /**
   * Generated by PHPUnit_SkeletonGenerator on 2012-05-17 at 14:37:31.
   */
  class InputTest extends \PHPUnit_Framework_TestCase
  {
    /**
     * @var Input
     */
    protected $object;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $this->object = new Input;
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    /**
     * @covers ADV\Core\Input::_post
     */
    public function testPost()
    {
      $_POST['test0'] = 'wawa';
      $expected       = 'wawa';
      $actual         = Input::post('test0');
      $this->assertSame($expected, $actual);
      $_POST['test0'] = '0';
      $expected       = '0';
      $actual         = Input::post('test0');
      $this->assertSame($expected, $actual);
      $expected = '';
      $actual   = Input::post('name', Input::STRING);
      $this->assertSame($expected, $actual);
      $expected = 'phil';
      $actual   = Input::post('name', Input::STRING, 'phil');
      $this->assertSame($expected, $actual);
      $_POST['test'] = 'ing';
      $this->assertSame('ing', Input::post('test'));
      $this->assertSame('ing', Input::post('test', Input::STRING));
      $this->assertSame('ing', Input::post('test', Input::STRING, ''));
      $this->assertSame(0, Input::post('test', Input::NUMERIC));
      $this->assertSame(0, Input::post('test', Input::NUMERIC, 0));
      $this->assertSame(1, Input::post('test', Input::NUMERIC, 1));
      $this->assertSame(null, Input::post('test2'));
      $this->assertEquals('', Input::post('test2'));
      $this->assertSame('', Input::post('test2', Input::STRING));
      $this->assertSame(0, Input::post('test2', Input::NUMERIC));
      $this->assertSame(5, Input::post('test2', Input::NUMERIC, 5));
      $_POST['test2'] = '0';
      $this->assertSame('0', Input::post('test2'));
      $this->assertSame('0', Input::post('test2', Input::STRING));
      $this->assertSame('0', Input::post('test2', Input::STRING, ''));
      $this->assertSame(0, Input::post('test2', Input::NUMERIC));
      $this->assertSame(0, Input::post('test2', Input::NUMERIC, 0));
      $this->assertSame(0, Input::post('test2', Input::NUMERIC, 1));
      $this->assertSame(null, Input::post('test3'));
      $this->assertEquals(0, Input::post('test3'));
      $_POST['test3'] = 7;
      $this->assertSame(7, Input::post('test3'));
      $this->assertSame('', Input::post('test3', Input::STRING));
      $this->assertSame('', Input::post('test3', Input::STRING, ''));
      $this->assertSame(7, Input::post('test3', Input::NUMERIC));
      $this->assertSame(7, Input::post('test3', Input::NUMERIC, 0));
      $this->assertSame(7, Input::post('test3', Input::NUMERIC, 1));
    }
    /**
     * @covers ADV\Core\Input::_get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
      $_GET['test0'] = 'wawa';
      $expected      = 'wawa';
      $actual        = Input::get('test0');
      $this->assertSame($expected, $actual);
      $_GET['test0'] = '0';
      $expected      = '0';
      $actual        = Input::get('test0');
      $this->assertSame($expected, $actual);
      $expected = '';
      $actual   = Input::get('name', Input::STRING);
      $this->assertSame($expected, $actual);
      $expected = 'phil';
      $actual   = Input::get('name', Input::STRING, 'phil');
      $this->assertSame($expected, $actual);
      $_GET['test'] = 'ing';
      $this->assertSame('ing', Input::get('test'));
      $this->assertSame('ing', Input::get('test', Input::STRING));
      $this->assertSame('ing', Input::get('test', Input::STRING, ''));
      $this->assertSame(0, Input::get('test', Input::NUMERIC));
      $this->assertSame(0, Input::get('test', Input::NUMERIC, 0));
      $this->assertSame(1, Input::get('test', Input::NUMERIC, 1));
      $this->assertSame(null, Input::get('test2'));
      $this->assertEquals('', Input::get('test2'));
      $this->assertSame('', Input::get('test2', Input::STRING));
      $this->assertSame(0, Input::get('test2', Input::NUMERIC));
      $this->assertSame(5, Input::get('test2', Input::NUMERIC, 5));
      $_GET['test2'] = '0';
      $this->assertSame('0', Input::get('test2'));
      $this->assertSame('0', Input::get('test2', Input::STRING));
      $this->assertSame('0', Input::get('test2', Input::STRING, ''));
      $this->assertSame(0, Input::get('test2', Input::NUMERIC));
      $this->assertSame(0, Input::get('test2', Input::NUMERIC, 0));
      $this->assertSame(0, Input::get('test2', Input::NUMERIC, 1));
      $this->assertSame(null, Input::get('test3'));
      $this->assertEquals(0, Input::get('test3'));
      $_GET['test3'] = 7;
      $this->assertSame(7, Input::get('test3'));
      $this->assertSame('', Input::get('test3', Input::STRING));
      $this->assertSame('', Input::get('test3', Input::STRING, ''));
      $this->assertSame(7, Input::get('test3', Input::NUMERIC));
      $this->assertSame(7, Input::get('test3', Input::NUMERIC, 0));
      $this->assertSame(7, Input::get('test3', Input::NUMERIC, 1));
    }
    /**
     * @covers ADV\Core\Input::_request
     * @todo   Implement testRequest().
     */
    public function testRequest()
    {
      $_GET['test3'] = 7;
      $this->assertSame(7, Input::get('test3'));
      $this->assertSame('', Input::get('test3', Input::STRING));
      $this->assertSame('', Input::get('test3', Input::STRING, ''));
      $this->assertSame(7, Input::get('test3', Input::NUMERIC));
      $this->assertSame(7, Input::get('test3', Input::NUMERIC, 0));
      $this->assertSame(7, Input::get('test3', Input::NUMERIC, 1));
      $_POST['test3'] = 7;
      $this->assertSame(7, Input::post('test3'));
      $this->assertSame('', Input::post('test3', Input::STRING));
      $this->assertSame('', Input::post('test3', Input::STRING, ''));
      $this->assertSame(7, Input::post('test3', Input::NUMERIC));
      $this->assertSame(7, Input::post('test3', Input::NUMERIC, 0));
      $this->assertSame(7, Input::post('test3', Input::NUMERIC, 1));
    }
    /**
     * @covers ADV\Core\Input::_getPost
     * @todo   Implement testgetPost().
     */
    public function testGetPost()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Input::_getPostGlobal
     * @todo   Implement testgetPostGlobal().
     */
    public function testgetPostGlobal()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Input::_postGlobal
     * @todo   Implement testpostGlobal().
     */
    public function testpostGlobal()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Input::_postGet
     * @todo   Implement testpostGet().
     */
    public function testpostGet()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Input::_session
     * @todo   Implement testSession().
     */
    public function testSession()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Input::_hasPost
     * @todo   Implement testhasPost().
     */
    public function testhasPost()
    {
      $this->assertSame(false, Input::hasPost('test'));
      $this->assertSame(false, Input::hasPost('test', 'test2'));
      $_POST['test'] = false;
      $this->assertSame(false, Input::hasPost('test', 'test2'), 'Should return false even if one variable is set.');
      $this->assertSame(true, Input::hasPost('test'), 'Should return true if post variable is set to false because it exists');
      $_POST['test2'] = null;
      $this->assertSame(false, Input::hasPost('test2'), 'Test2 is set but is null so it should return false!');
      $this->assertSame(false, Input::hasPost('test', 'test2'), 'Both are set but test2 is set but is null so it should return false!');
      $_POST['test2'] = 'something';
      $this->assertSame(true, Input::hasPost('test', 'test2'), 'Both are set but test2 is set but is null so it should return false!');
    }
    /**
     * @covers ADV\Core\Input::_hasGet
     * @todo   Implement testhasGet().
     */
    public function testhasGet()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Input::_has
     * @todo   Implement testHas().
     */
    public function testHas()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Input::_hasSession
     * @todo   Implement testhasSession().
     */
    public function testhasSession()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
    /**
     * @covers ADV\Core\Input::_has
     * @todo   Implement test_has().
     */
    public function test_has()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete('This test has not been implemented yet.');
    }
  }
