<?php

require_once 'C:\dev\accounts\includes\app\search.php';

/**
 * Test class for Search.
 * Generated by PHPUnit on 2011-12-24 at 14:09:41.
 */
class SearchTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Search
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Search(null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testSetOptions().
     */
    public function testSetOptions()
    {

			$options =array('cells'=>true,'js'=>false,'horse'=>'goat');
			$result = $this->object->setOptions($options);
			$expected = array('cells'=>true,'js'=>false);
			$this->assertEquals($expected,$result);

    }


}
?>
