<?php

	/*
		Do not edit this file manually. This copy of global file is overwritten
		by extensions editor.
	*/

	$installed_extensions = array(
		1 => array('tab' => 'system',
			'name' => 'Advanced',
			'path' => 'advanced',
			'title' => 'Advanced',
			'active' => '1',
			'type' => 'plugin',
			'filename' => 'advanced.php',
			'acc_file' => 'acc_levels.php',
			'access' => 'SA_ADVANCED',
		),
	);
?>