<?php
/**
 * Created by JetBrains PhpStorm.
 * User: root
 * Date: 1/9/11
 * Time: 4:00 PM
 * To change this template use File | Settings | File Templates.
 */
class PurchaseOrder extends Orders {



	public $supplier_id;
	public $requisition_no;
	public $into_stk_loc;

	protected function _canProcess() {
		// TODO: Implement _canProcess() method.
	}
	protected function _countTransactions() {
		// TODO: Implement _countTransactions() method.
	}
	protected function _defaults() {
		// TODO: Implement _defaults() method.
	}
	protected function _new() {
		// TODO: Implement _new() method.
	}
	protected function _read() {
		// TODO: Implement _read() method.
	}
	protected function _saveNew() {
		// TODO: Implement _saveNew() method.
	}
	public function delete() {
		// TODO: Implement delete() method.
	}
	public function save($changes = null) {
		// TODO: Implement save() method.
	}
}
